FROM node:22 AS builder


WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm install -f


COPY . .

RUN npm run build

FROM node:22
WORKDIR /app
COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm npm install -f --omit=dev

COPY --from=builder /app/dist ./dist 
COPY ./prisma ./prisma

EXPOSE 4000

CMD npm run prisma:generate && node --watch dist/main.js