services:
  # nest-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-api
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - nest-postgres
  #   env_file:
  #     - .env

  nest-postgres-serv:
    image: postgres:14
    container_name: nest-postgres-serv
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - nest-postgres-serv:/var/lib/postgresql/data

volumes:
  nest-postgres-serv:
    name: nest-postgres-db
